### ISSUE TITLE
Can't connect Flic. Possible problem with server?

### ISSUE THREAD

**Issue by johnkjellberg** [50ButtonsEach/fliclib-linux-dist#2]
After some struggling i got to the point where I after a "connect `<my flic mac>`" got the following response:

`https://testapi.flic.io/api/v1/buttons/<some-uid>/unlock [<my flic mac>]`
{"appId":"`<some other uuid>`","appSecret":"`<some other other uuid>`","r1":-5490344220530841045,"r2":2710058410323377349} [`<my flic mac>`]
Failed to request unlock endpoint: HTTP status code 6 [`<my flic mac>`]

**Comment by fabianbergmark** [comment]
Hi

Something is definitely strange. the appId and appSecret fields should never be empty, also there is a part of the URL missing. Did you leave these out or are they missing? Status code 6 apparently means there was an SSL error (SOUP_STATUS_SSL_FAILED). Any idea why? I will look into this tomorrow

**Comment by johnkjellberg** [comment]
Sorry. I tried to replace the ID's with placeholders since I didn't know if any of the information might be sensitive. I did edit the comment a couple of times to fix the markup. It looks fine on my side now.
So, no, nothing is empty.
Should I paste an "uncensored" version including my FLIC MACs?

**Comment by johnkjellberg** [comment]
Don't know what the SSL-problem might be. I tried to do a curl GET-request on that URL and got a (error) response from your server.

**Comment by fabianbergmark** [comment]
Be sure to set the content type to application/json. Could you include the curl request to help us with debugging? Send it to fabian@shortcutlabs.com with all UUIDs and secrets

**Comment by fabianbergmark** [comment]
we are seeing this on our side

```
2016/01/25 21:19:59 [crit] 4266#0: *619 SSL_do_handshake() failed (SSL: error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback) while SSL handshaking, client: *.*.*.*, server: 0.0.0.0:443
2016/01/25 21:21:08 [crit] 4266#0: *844 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: *.*.*.*, server: 0.0.0.0:443
2016/01/25 21:21:08 [crit] 4266#0: *845 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: *.*.*.*, server: 0.0.0.0:443
```

**Comment by fabianbergmark** [comment]
Apparently there is something wrong with daemon related to SSL. I will look into this tomorrow at work. Thanks for all the information!

**Comment by fabianbergmark** [comment]
I changed so that glib-libraries are linked dynamically. Users might have to install some packages but at least it works. I will upload a new release tonight

**Comment by fabianbergmark** [comment]
There is a new release, it should solve these issues.

**Comment by johnkjellberg** [comment]
That fixed the problem. Now running the x86_64 version and it connects to my Flic and detects pushes!
