### ISSUE TITLE
Possible to use a full-stack device?

### ISSUE THREAD

**Issue by ryjogo** [50ButtonsEach/fliclib-linux-dist#24]
I have a full-stack bluetooth device which loads up in my pi fine. However it doesn't support HCI 
http://docs-europe.electrocomponents.com/webdocs/12eb/0900766b812eb651.pdf
https://www.bluegiga.com/en-US/products/bled112-bluetooth-smart-dongle/

Any ideas?

**Comment by fabianbergmark** [comment]
No, HCI is needed
