### ISSUE TITLE
make fails on Beaglebone Black (Jesse)

### ISSUE THREAD

**Issue by ryanshuck** [50ButtonsEach/fliclib-linux-dist#25]
Here's where it failed. Any ideas?

`CC       src/bluetoothd-plugin.o
src/plugin.c: In function ‘plugin_init’:
src/plugin.c:139:14: error: ‘__bluetooth_builtin’ undeclared (first use in this function)
  for (i = 0; __bluetooth_builtin[i]; i++) {
              ^
src/plugin.c:139:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:8106: recipe for target 'src/bluetoothd-plugin.o' failed
make[1]: *** [src/bluetoothd-plugin.o] Error 1
Makefile:3126: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by fabianbergmark** [comment]
I haven't experienced this myself. Try checking out an older bluez version (maybe tag 5.37) in git. #bluez on irc.freenode.net is also a good way to get help

**Comment by ryanshuck** [comment]
This is 5.37, unfortunately. I will ask in #bluez and see if they can help me work this out. Thanks.
