### ISSUE TITLE
Not running on Ubuntu 14.04 

### ISSUE THREAD

**Issue by NikolasE** [50ButtonsEach/fliclib-linux-dist#31]
The binaries are not running on 14.04 even though this is the current LTS version of Ubuntu. 

./daemon: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./daemon)
./daemon: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version`CXXABI_1.3.9' not found (required by ./daemon)
./daemon: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./daemon)

Could you also provide binaries for the LTS version?

**Comment by fabianbergmark** [comment]
When I'm releasing this library, I will make sure it will run on older platforms. However, due to limited time, this beta is limited to the stated platforms.

**Comment by NikolasE** [comment]
Are you going to release the code so that I can build it myself?

**Comment by fabianbergmark** [comment]
We are discussing that for the release, but not for the beta

**Comment by mrmstn** [comment]
+1 for releasing the code

**Comment by Ziemowit** [comment]
Are you able give approximate date when new version will be released?
I need it to finish my task ;]

**Comment by fabianbergmark** [comment]
Are you having the same glibc/libstdc++ version problems? Those won't be fixed until release which might be a while. I would suggest updating your system, installing a new g++ should do it

**Comment by Ziemowit** [comment]
No I have problem with build in bluetooth (more than one bluetooth on comupter) when one of them does not support version 4.0.
