### ISSUE TITLE
Failed to start scan: no adapters

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-dist#37]
Hi All

I followed the steps in the readme and now when I run the startScan command I get a message in the window running the daemon - Failed to start scan no adapters.

I assume that this means it's not able to find any bluetooth adapters. I did disable the bluetoothd service, clone bluez and follow the instructions to compile and run it.

Very new to linux so this is all new to me.

This is on Raspbian on a pi 3.

**Comment by fabianbergmark** [comment]
Check in hciconfig which adapters are available. I think raspberrypi 3 only has drivers on the latest raspbian

**Comment by Roaders** [comment]
Ah - hciconfig wasn't up. Started it and now getting a bit further
