### ISSUE TITLE
Result: WizardFailedTimeout

### ISSUE THREAD

**Issue by luahana** [50ButtonsEach/fliclib-linux-dist#45]
I am currently working on Windows Flic Client.

I have downloaded FlicSDK and ran on localhost port: 5551 and ran FlicLibTest program. 
I succeeded to connect to the FlicSDK and tried to add new Flic by pressing "Add new Flic" button

When I press the Flic button, the program is able to connect the Flic button, but it does not want to pair.
saying" "Connected to [Flic address], now pairing..." for 30s, then Result: WizardFailedTimeout shows.

I have 4 Flic buttons and tried all of them but I don't know why it isn't working.

I have read protocol documentation and I am guessing my pc and the Flic button don't verify each other.

Any help much appreciated.

**Comment by Emill** [comment]
What revision do your buttons have? You see it in the name. It's character 2 to 4.

**Comment by Emill** [comment]
Also, are you running the server on Windows or Linux?

**Comment by luahana** [comment]
sorry I should have written this on windows issues page.

This is Windows.

2 of them start with F016 and the other 2 start with F018.

**Comment by Emill** [comment]
Please use Android or iOS to first update to revision 20

**Comment by luahana** [comment]
Could you write out or link me the instruction on updating them?

I have paired them with my Samsung Galaxy S6 and it didn't do any update yet (if it is supposed to update automatically.)

Thanks.

**Comment by Emill** [comment]
Yes let them be connected for a while and they should update automatically.

**Comment by luahana** [comment]
It's not updating now I guess it is because my phone is not in wifi zone.

I will try it at home.

Thank you very much for your quick help.

**Comment by luahana** [comment]
Hi, it's me again.

They automatically updated to f022 and I am having the same issue.

**Comment by Emill** [comment]
Could you tell which exact windows build number you have? And also what Bluetooth chip you have in your computer.

**Comment by luahana** [comment]
Windows10 : Version 1607 (OS Build 14393.321)

I am using bluetooth dongle : USB-BT400 Bluetooth 4.0 USB Adapter by Asus

**Comment by Emill** [comment]
I'll continue with this in two week since I'll be away for holiday. The strange thing is that I have the same setup as you have... I'm going to send over a debug version so the problem can be identified.

**Comment by luahana** [comment]
Thank you if you send me the FlicSDK code or upload it in git it would be
really helpful.

**Comment by Emill** [comment]
Yes I'll do that as soon as I'm back

**Comment by Emill** [comment]
@luahana Can you try this debug version?
https://drive.google.com/open?id=0B-kW5rSvtUYnREl0TzlKNHhhTW8
It will print out some logs. Post the output here.

**Comment by luahana** [comment]
I tried this and I got this:

Bluetooth radio was attached!
Register notifications
Restart
connected
subscribed button char
Read a packet:
4200000000000000000000000000000000000000
Doing full verify
Wrote 0700b9bc33d5d3142926, result: 00000000
Looking for notification
notification 0011
Found notification
Looking for notification
notification 0011
Found notification
Doing web request
disconnected
connected
disconnected
connected
disconnected
connected
disconnected
connected
disconnected
connected
disconnected

...

**Comment by Emill** [comment]
Do you have some firewall that blocks internet for FlicSDK.exe?

**Comment by luahana** [comment]
how do i check if the firewall is blocking internet for FlicSDK.exe?

**Comment by Emill** [comment]
Do you have some special firewall application installed or are you just using Windows Firewall?
If you only have Windows Firewall, simply try to turn it off temporarily.

**Comment by luahana** [comment]
yeah I am working with a company's computer so there must be special firewall

**Comment by Emill** [comment]
Then make sure FlicSDK.exe has access to internet to do outbound TCP connections on port 443.

**Comment by luahana** [comment]
Just wondering, does that mean the Flic won't work when there is no internet connection?

**Comment by Emill** [comment]
You only need internet connection the first time each Flic is connected.

**Comment by luahana** [comment]
Is there a way to connect Flic without internet connection? We want to use Flics where there is no internet access. And we certainly don't want to bring 100s of computers up to have them connected to internet just in order to connect to Flics.

**Comment by Emill** [comment]
As I said, you need internet the first time a button is paired to a specific Bluetooth controller.

If you have external dongles you can connect them to a computer that has internet and later plug it in to another computer and copy over the pairing info in HKEY_CURRENT_USER\SOFTWARE\Shortcut Labs.
