### ISSUE TITLE
Update suggestions to readme

### ISSUE THREAD

**Issue by CheapB** [50ButtonsEach/fliclib-linux-dist#5]
I suggest following updates to the Readme based on a fairly clean RPI Jessie install: 

Requirements:
Following needs to be installed if not present on your system already:
libglib2.0-0 
libglib2.0-dev
libdbus-1-dev
libudev-dev
automake
libtool

install with: sudo apt-get install <req.lib>

example: 
"./daemon -l -f flic.sqlite3" needs to be "sudo ./daemon -l -f flic.sqlite3" 

tips: 

If you get the error message "D-Bus setup failed: Name already in use" you can try "ps aux | grep blue" and then "Sudo kill <pid>" for the appropriate process

the device may be down for various reasons. try "sudo hciconfig hci0 up"

Not all flic glows in public mode. if you cant get it to do so - just hold it for 8+ sec while you try to connect.

**Comment by KaiboshOz** [comment]
Appreciate the post CheapB..  After getting most of the way, I was having trouble with the scan.  I'm using a different BT adapter than the 2 noted, so I figured it was that.
Lo and behold, it was the need to bring the device up (which I recall seeing mentioning amongst my huge amount of googling yesterday, and was one of the things on a long list to try when I resumed).

**Comment by CheapB** [comment]
there are actually a number of other libraries required that I already had installed. I will try to compile a complete list

**Comment by CheapB** [comment]
The complete prerequisites for BlueZ on RPI/Jessie can be found here. Not sure if this is relevant for all platforms or not https://github.com/50ButtonsEach/fliclib-linux-dist/issues/10
