### ISSUE TITLE
Beta 3 armv7l does not work on clean raspberry Pi Jessie

### ISSUE THREAD

**Issue by CheapB** [50ButtonsEach/fliclib-linux-dist#9]
Doing a clean install on a RPI with Jessie and I am getting  `GLIBCXX_3.4.21' not found (required by ./daemon)

did apt-get update  and apt-get upgrade

armv6I does not have the same problem

**Comment by fabianbergmark** [comment]
I might have built this on a arch installation by mistake. I will check tomorrow. The armv6l should be somewhat usable on armv7l

**Comment by fabianbergmark** [comment]
I rebuilt the armv7l version on a clean Jessie installation, could you confirm that it works now?

**Comment by CheapB** [comment]
I can confirm it is executing. I cant seem to get the CLI to recognize the messages, but I will have to investigate a bit more before reporting back on it. It may be an unrelated issue
![arm7](https://cloud.githubusercontent.com/assets/5741458/12684920/50d40868-c68f-11e5-8f48-995745d1c091.JPG)

**Comment by CheapB** [comment]
The issue described above is not related to arm7 - I suddenly have the same issue on arm6 and 7 on both beta 2 and 3.

**Comment by fabianbergmark** [comment]
Be sure to run bluetoothd with the -E flag (or -nEd if you run it from console like you seem to do). Also you can type list in the flic executable to se already known buttons.
